#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import csv
from pathlib import Path

module_id = "geologia-avancado-m14"

# BASIC CARDS (question-answer)
basic_cards = [
    # Aula 01 - Conceitos, plataformas, sensores
    (f"{module_id}-fb001", "O que é resolução espacial?", "Tamanho de cada pixel no terreno, em metros. Define o menor detalhe observável.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fb002", "Qual a diferença entre resolução espacial e resolução espectral?", "Espacial: tamanho do pixel. Espectral: número e largura das bandas observadas.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fb003", "O que é resolução temporal?", "Frequência com que um sensor revê o mesmo lugar (ex: 5 dias, 16 dias).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fb004", "O que é resolução radiométrica?", "Número de níveis de cinza por banda (ex: 8-bit = 0–255, 11-bit = 0–2047).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fb005", "Como funciona uma composição colorida em sensores multiespectrais?", "Atribui três bandas aos canais RGB (vermelho, verde, azul) do monitor. Combinações diferentes realçam alvos diferentes.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fb006", "Qual é o padrão de composição natural?", "Bandas que correspondem ao espectro visível (em sensores ópticos, ex: R-G-B = NIR-Red-Green para muitos sensores).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fb007", "Por que usamos composições de SWIR em geologia?", "SWIR (Short-Wave InfraRed) mostra absorções de minerais (silicatos, óxidos, argilominerais) que não aparecem no visível.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "alta"),
    (f"{module_id}-fb008", "Quantas bandas SWIR tem o sensor OLI do Landsat?", "Duas bandas: banda 6 (1,57–1,65 µm) e banda 7 (2,10–2,29 µm).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fb009", "O que significa espaço-tempo em sensoriamento remoto?", "Compromisso entre as quatro resoluções: melhorar uma custeia nas outras três. Sensores de resolução fina cobrem áreas pequenas ou têm revisita lenta.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "alta"),
    (f"{module_id}-fb010", "Qual é a principal constelação de satélites ópticos de resolução média?", "Sentinel-2: dois satélites (2B + 2C desde janeiro/2025), 13 bandas, 10–60 m de resolução, 5 dias de revisita.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),

    # Aula 02 - Física da radiação
    (f"{module_id}-fb011", "O que é a lei de Planck?", "Descreve a intensidade de radiação emitida por um corpo negro em função do comprimento de onda e da temperatura.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "alta"),
    (f"{module_id}-fb012", "Qual é a diferença entre reflectância e emitância?", "Reflectância: fração da radiação incidente refletida. Emitância: radiação emitida pelo objeto em função de sua temperatura.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "alta"),
    (f"{module_id}-fb013", "O que é path radiance?", "Radiação espalhada pela atmosfera que chega ao sensor sem ter tocado o alvo — ruído que reduz contraste da imagem.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "média"),
    (f"{module_id}-fb014", "Por que bandas no visível sofrem mais atenuação atmosférica que bandas no infravermelho próximo?", "Absorção por Rayleigh é inversamente proporcional a λ⁴. Comprimentos de onda mais curtos (azul) espelham muito mais.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "alta"),
    (f"{module_id}-fb015", "O que é uma janela atmosférica?", "Intervalo de comprimento de onda onde a atmosfera é transparente (deixa passar radiação). Sensores são projetados para operar nessas janelas.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "média"),
    (f"{module_id}-fb016", "Qual é a principal janela atmosférica no visível-infravermelho próximo?", "0,4–1,1 µm (visível e NIR). Na região termal: 8–14 µm (banda das emitâncias).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "média"),

    # Aula 03 - Comportamento espectral
    (f"{module_id}-fb017", "O que é a assinatura espectral de um alvo?", "Padrão de reflectância ou emitância em função do comprimento de onda que caracteriza um material. Permite identificação.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "média"),
    (f"{module_id}-fb018", "Por que a água absorve muito no infravermelho próximo e médio?", "Vibrações de estiramento e flexão das moléculas H–O–H produzem picos de absorção centrados em ~0,94 µm, ~1,1 µm e ~1,4 µm.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fb019", "O que é uma argilomineral e por que é importante em sensoriamento remoto?", "Silicato com estrutura de camadas (caulinita, esmectita, etc) com absorções fortes no SWIR (~2,2 µm) que identificam tipos de alteração mineral.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fb020", "Qual é o mecanismo que produz a feição de absorção de óxidos de ferro em 0,87–0,92 µm?", "Transição de CAMPO CRISTALINO do Fe³⁺ (não transferência de carga). A posição discrimina hematita (~0,86 µm) de goethita (~0,90–0,92 µm).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fb021", "Qual é o mecanismo da feição de absorção de óxidos de ferro no visível (~0,4–0,6 µm)?", "Transferência de carga (LCMT) do O²⁻ para Fe³⁺, com pico no ultravioleta próximo (~0,25 µm); a cauda invade o visível causando a cor vermelha/marrom dos lateritos.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fb022", "O que é geobotânica em sensoriamento remoto?", "Detecção indireta de minerais/anomalias geoquímicas via resposta espectral de plantas que crescem sobre esses materiais (estresse, deficiência, vigor alterado).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "média"),
    (f"{module_id}-fb023", "Por que o NDVI é sensível à vegetação?", "NDVI = (NIR − Red)/(NIR + Red). Vegetação saudável reflete muito no NIR (poucos danos) e absorve no Red (fotossíntese), gerando NDVI > 0,5.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "média"),

    # Aula 04 - PDI I
    (f"{module_id}-fb024", "O que é uma operação aritmética entre bandas?", "Combinação algébrica de dois rasters pixel a pixel (ex: diferença, razão, soma) para realçar atributos específicos.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "média"),
    (f"{module_id}-fb025", "O que é um índice de banda?", "Razão ou combinação linear de bandas normalizada para criar um novo raster que ressalta propriedade específica (ex: NDVI para vegetação, NDWI para água).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "média"),
    (f"{module_id}-fb026", "Por que uma razão de bandas (ex: NIR/Red) cancela efeitos de sombra e iluminação?", "Porque a sombra atenua ambas as bandas proporcionalmente; a razão remove a escala comum de brilho.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "alta"),
    (f"{module_id}-fb027", "O que é um filtro de convolução?", "Matriz de pesos (kernel) que desliza sobre cada pixel e seus vizinhos para calcular novo valor via soma ponderada dos vizinhos.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "média"),
    (f"{module_id}-fb028", "Qual é a finalidade de um filtro Laplaciano?", "Ressaltar bordas detectando mudanças rápidas de valor entre pixels vizinhos (segunda derivada espacial).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "média"),
    (f"{module_id}-fb029", "O que faz um filtro mediano diferente de um Gaussiano?", "Mediano: substitui pixel pelo valor mediano dos vizinhos (robusto a outliers, bom para ruído). Gaussiano: média ponderada (suaviza gradualmente).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "média"),

    # Aula 05 - PDI II
    (f"{module_id}-fb030", "O que é Análise de Componentes Principais (ACP)?", "Transformação linear que cria novos rasters (componentes) ao encontrar direções de máxima variância nos dados multiespectrais.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "alta"),
    (f"{module_id}-fb031", "Por que PC1 (primeira componente principal) não é garantida ser a mais informativa geologicamente?", "Porque PC1 maximiza variância total (que pode ser brilho solar). Variância máxima ≠ sinal diagnóstico.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "alta"),
    (f"{module_id}-fb032", "Qual é a diferença entre classificação supervisionada e não supervisionada?", "Supervisionada: requer amostras de treinamento do usuário (ex: máxima verossimilhança). Não supervisionada: agrupa pixels automaticamente (ex: K-means).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "alta"),
    (f"{module_id}-fb033", "O que é uma matriz de confusão?", "Tabela que compara classificação produzida vs verdade de campo, mostrando acertos por classe e erros de comissão/omissão.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "média"),
    (f"{module_id}-fb034", "Qual é a diferença entre acurácia global e acurácia do produtor?", "Global: (diagonais)/(total). Produtor: acertos de uma classe / total dessa classe no terreno (sensibilidade).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "alta"),

    # Aula 06 - Sensoriamento ativo
    (f"{module_id}-fb035", "Como funciona um radar de abertura sintética (SAR)?", "Sensor ativo que emite micro-ondas e mede a energia retornada (retroespalhamento) e o tempo de retorno. Movimento de plataforma sintetiza grande abertura de antena.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb036", "Qual é a resolução azimutal de um SAR?", "~D/2, onde D é o comprimento da antena física. Independente do comprimento de onda λ (ele se cancela na síntese).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb037", "O que é encurtamento (foreshortening) em SAR?", "Distorção onde feições inclinadas na direção de visada aparecem comprimidas no terreno, reduzindo comprimento aparente.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb038", "O que é layover (sobreposição) em SAR?", "Distorção onde o topo de um elemento topográfico retorna para o radar antes de sua base, invertendo ordem de visibilidade na imagem.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb039", "O que é sombra de radar?", "Área sem retroespalhamento observado porque a encosta voltada para o sensor é bloqueada pela topografia mais alta atrás.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb040", "Como a declividade (α) e o ângulo de incidência (θ) determinam encurtamento/layover/sombra?", "Se α < θ: encurtamento. Se α > θ: layover. Se encosta oposta > 90°−θ: sombra nela.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb041", "O que é um interferograma SAR (InSAR)?", "Imagem de fase relativa entre dois (ou mais) SAR de mesma cena, revelando deslocamento do terreno sub-milimétrico via franjas de interferência.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb042", "O que é coerência em interferometria?", "Medida (0–1) de quanto o padrão de retroespalhamento permaneceu constante entre as aquisições; vegetação densa reduz coerência.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb043", "Como se converte uma franja InSAR em deslocamento?", "Cada volta de franja = λ/2 de deslocamento (ex: Sentinel-1 banda C, λ~5,6 cm, 1 franja = 2,8 cm).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fb044", "O que é LiDAR?", "Light Detection and Ranging: sensor ativo que emite pulsos laser e mede tempo de retorno para mapear topografia com precisão de decímetros.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "média"),
    (f"{module_id}-fb045", "O que é retorno múltiplo em LiDAR?", "Um pulso pode retornar múltiplas vezes (topo da copa, meio da árvore, solo), revelando estrutura 3D da vegetação.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "média"),

    # Aula 07 - Fotogrametria e termal
    (f"{module_id}-fb046", "O que é fotogrametria digital (SfM)?", "Structure from Motion: técnica que constrói modelo 3D a partir de fotos sobrepostas, detectando pontos-chave e triangulando sua posição.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb047", "O que são GCPs em fotogrametria?", "Ground Control Points: pontos de controle medidos no terreno (GPS) que amarram coordenadas do modelo 3D ao sistema geográfico real.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "média"),
    (f"{module_id}-fb048", "Por que GCPs não distorcem a geometria relativa de um modelo SfM?", "Porque SfM constrói geometria interna via triangulação de homólogos. GCPs só escalam e reposicionam, sem mudar a forma relativa.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb049", "O que é um ortomosaico?", "Imagem ortorretificada montada de múltiplas fotos (remove distorção de perspectiva e variação de relevo), pronta para medições.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "média"),
    (f"{module_id}-fb050", "Por que fotogrametria falha sob vegetação densa?", "Porque as câmeras não veem o solo (só folhagem), impossibilitando detecção de pontos-chave para triangulação.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "média"),
    (f"{module_id}-fb051", "Qual é o princípio da radiometria termal?", "Objetos com temperatura > 0 K emitem radiação infravermelha; um sensor termal mede essa radiação por banda espectral.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "média"),
    (f"{module_id}-fb052", "O que descreve a lei de Stefan-Boltzmann?", "Relaciona exitância radiante INTEGRADA (sobre todos os comprimentos de onda) com a temperatura: M = ε·σ·T⁴.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb053", "Como se converte radiância spectral (medida pelo sensor termal) em temperatura?", "Invertendo a lei de PLANCK, não Stefan-Boltzmann. Planck descreve distribuição espectral de radiância.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb054", "O que é a feição de Christiansen?", "MÁXIMO de emissividade (não mínimo) entre 7–9 µm, onde o índice de refração do material se aproxima do meio (ar).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb055", "O que são bandas de reststrahlen?", "MÍNIMOS de emissividade, correspondentes a vibrações fundamentais de estiramento Si–O em silicatos, ~8–12 µm.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb056", "Como se desloca a feição de Christiansen com a composição de silicatos?", "~7,5–8,0 µm em rochas félsicas (alto SiO₂) para ~8,5–9,0 µm em máficas/ultramáficas (baixo SiO₂). Deslocamento contraintuitivo: mais SiO₂ → onda mais CURTA.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb057", "Por que a banda 11 do Landsat 8/9 TIRS é desaconselhada para análise quantitativa?", "Porque tem incerteza radiométrica residual (~1,7 K) por luz espúria captada de fora do campo de visão; USGS recomenda canal único sobre banda 10.", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fb058", "O que é diferença de temperatura (ΔT) em análise termal?", "Variação de temperatura entre áreas distintas observadas pelo sensor (ex: 14 K entre pilha de rejeito aquecida e terreno adjacente).", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "média"),
]

# CLOZE CARDS
cloze_cards = [
    (f"{module_id}-fc001", "Resolução espacial de {{c1::30 metros}} = cada pixel representa {{c2::900 metros quadrados}} de terreno (30 × 30 m).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fc002", "O Landsat tem resolução VNIR (visível-NIR) de {{c1::30 metros}} e SWIR de {{c2::30 metros}}, mas banda termal em {{c3::100 metros}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fc003", "Sentinel-2 tem 13 bandas com resolução variável: {{c1::10 metros}} (R, G, B, NIR), {{c2::20 metros}} (SWIR, vapor de água), {{c3::60 metros}} (aerossol, cirro).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fc004", "Sentinel-2: arranjo de {{c1::dois satélites}} (2B e 2C desde janeiro/2025), 5 dias de revisita, defasados 180 graus.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fc005", "ASTER tem {{c1::14 bandas}}, de {{c2::0,5 a 14 micrometros}}, com resolução VNIR de {{c3::15 metros}} e TIR de {{c4::90 metros}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fc006", "{{c1::VNIR}} = Visível + Infravermelho Próximo (0,4–1,1 µm). {{c2::SWIR}} = Infravermelho Médio (1,3–3,0 µm). {{c3::TIR}} = Termal (8–14 µm).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa02", "geologia-avancado-m14-a01", "média"),
    (f"{module_id}-fc007", "Espalhamento de Rayleigh (proporção {{c1::λ⁻⁴}}) é {{c2::maior}} para comprimentos de onda {{c3::curtos}} (azul); responsável pela cor azul do céu.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "alta"),
    (f"{module_id}-fc008", "Camada de {{c1::ozônio}} absorve radiação ultravioleta; {{c2::vapor de água}} absorve infravermelho próximo (~0,9, 1,1, 1,4 µm); {{c3::dióxido de carbono}} absorve no termal.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "média"),
    (f"{module_id}-fc009", "Janela atmosférica no visível-NIR: {{c1::0,4–1,1 micrometros}}. Janela termal: {{c1::8–14 micrometros}} (TIRS do Landsat opera nesta faixa).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a02", "média"),
    (f"{module_id}-fc010", "Hematita tem absorção de campo cristalino em {{c1::~0,86 micrometros}}. Goethita em {{c2::~0,90–0,92 micrometros}}. AMBAS são {{c3::transições de campo cristalino}} do Fe³⁺, não transferência de carga.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fc011", "Transferência de carga (LCMT) O²⁻ → Fe³⁺ fica no {{c1::ultravioleta próximo (~0,25 micrometros)}}; a {{c2::cauda}} dela invade o visível causando a cor vermelha/marrom dos {{c3::lateritos}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fc012", "Caulinita tem absorção forte no SWIR em {{c1::~2,2 micrometros}}. Esmectita em {{c2::~2,3 micrometros}}. Ambas indicam {{c3::alteração de feldspato}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fc013", "Água absorve fortemente em {{c1::~0,94, 1,1, 1,4 micrometros}} (vibrações de H–O–H), tornando-se {{c2::escura}} em qualquer banda do {{c3::NIR/SWIR}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "média"),
    (f"{module_id}-fc014", "NDVI = ({{c1::NIR}} − {{c2::Red}}) / ({{c3::NIR}} + {{c4::Red}}). Vegetação saudável: NDVI > {{c5::0,5}}. Solo exposto: NDVI < {{c6::0,2}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "média"),
    (f"{module_id}-fc015", "{{c1::McFeeters (1996)}} definiu NDWI para {{c2::água superficial}}: ({{c3::Verde}} − {{c4::NIR}}) / (Verde + NIR).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "média"),
    (f"{module_id}-fc016", "{{c1::Gao (1996)}} definiu um índice {{c2::homonimo}} NDWI para {{c3::água foliar}}: (NIR − SWIR) / (NIR + SWIR). É índice de {{c4::vegetação}}, não de água superficial.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a03", "alta"),
    (f"{module_id}-fc017", "NDVI sob sombra parcial: numerador (NIR − Red) e denominador (NIR + Red) ambos {{c1::reduzem}} proporcionalmente. A {{c2::razão}} cancela o efeito e permanece {{c3::igual}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "alta"),
    (f"{module_id}-fc018", "Realçamento linear de contraste estira histograma de uma banda para usar {{c1::100%}} da escala (0–255 em 8-bit), aumentando {{c2::contraste}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "média"),
    (f"{module_id}-fc019", "Filtro Laplaciano ressalta {{c1::bordas}} usando {{c2::segunda derivada}} (matriz com {{c3::–4, +1, +1, +1, +1}} no kernel).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a04", "média"),
    (f"{module_id}-fc020", "Primeira componente principal (PC1) maximiza {{c1::variância}}, não {{c2::informação geológica}} — pode ser apenas brilho solar.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "alta"),
    (f"{module_id}-fc021", "Classificação {{c1::não supervisionada}} (ex: {{c2::K-means}}) agrupa pixels {{c3::automaticamente}}. Classificação {{c4::supervisionada}} (ex: {{c5::máxima verossimilhança}}) requer {{c6::amostras de treinamento}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "média"),
    (f"{module_id}-fc022", "Acurácia do produtor = (acertos de uma classe) / (total dessa {{c1::classe no terreno}}). Mede {{c2::sensibilidade}}: quanto da classe real foi corretamente {{c3::identificado}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "alta"),
    (f"{module_id}-fc023", "Acurácia do usuário = (acertos de uma classe) / (total de pixels {{c1::classificados como aquela classe}})). Mede confiabilidade da {{c2::classe produzida}} no mapa.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa03", "geologia-avancado-m14-a05", "alta"),
    (f"{module_id}-fc024", "Resolução azimutal do SAR = {{c1::D/2}}, onde D = comprimento da {{c2::antena física}}. {{c3::Independente}} de {{c4::comprimento de onda}} (λ se cancela na síntese).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fc025", "Encurtamento, layover e sombra de radar comparecem segundo a relação entre {{c1::declividade}} (α) e {{c2::ângulo de incidência}} (θ) do radar.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fc026", "Se {{c1::α > θ}}, ocorre {{c2::layover}} (inversão de ordem na imagem). Se {{c1::α < θ}}, {{c3::encurtamento}} (compressão).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fc027", "Sombra de radar em encosta oposta ocorre quando sua declividade excede {{c1::90° − θ}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fc028", "Uma franja InSAR corresponde a deslocamento de {{c1::λ/2}} (ex: Sentinel-1 banda C, λ ≈ {{c2::5,6 cm}}, logo 1 franja = {{c3::2,8 cm}})).", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fc029", "Coerência em interferometria: medida de {{c1::0 a 1}} indicando quanto o {{c2::padrão de retroespalhamento}} permaneceu {{c3::constante}} entre acquisições. {{c4::Vegetação densa}} reduz coerência.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "alta"),
    (f"{module_id}-fc030", "LiDAR = {{c1::Light Detection and Ranging}}, sensor {{c2::ativo}} que mede tempo de retorno de {{c3::pulsos laser}}, produzindo modelo 3D sub-métrico.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a06", "média"),
    (f"{module_id}-fc031", "{{c1::Structure from Motion (SfM)}}: fotogrametria que detecta pontos-chave em múltiplas fotos e {{c2::triangula}} posição 3D automaticamente.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fc032", "GCPs (Ground Control Points) {{c1::escalam e reposicionam}} modelo SfM, sem alterar {{c2::geometria relativa}} dos pontos internos.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa04", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fc033", "Lei de Stefan-Boltzmann: M = {{c1::ε}} · {{c2::σ}} · {{c3::T⁴}}, relaciona {{c4::exitância radiante INTEGRADA}} (não radiância de banda) com {{c5::temperatura}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fc034", "Para converter radiância espectral (medida pelo sensor termal) em temperatura, inverte-se a {{c1::lei de Planck}}, não Stefan-Boltzmann.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fc035", "Feição de Christiansen: {{c1::MÁXIMO}} de emissividade (não mínimo), ~{{c2::7–9 micrometros}}, onde índice de refração se aproxima do meio.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fc036", "Bandas de reststrahlen: {{c1::MÍNIMOS}} de emissividade, vibrações Si–O, {{c2::~8–12 micrometros}}, {{c3::posição oposta}} a Christiansen.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fc037", "Feição de Christiansen: {{c1::~7,5–8,0 micrometros}} em {{c2::félsicas}} (alto SiO₂); {{c3::~8,5–9,0 micrometros}} em {{c4::máficas}} (baixo SiO₂). Deslocamento {{c5::contraintintuitivo}}: mais SiO₂ → onda mais {{c6::CURTA}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
    (f"{module_id}-fc038", "Landsat 8/9 TIRS: banda {{c1::10}} recomendada para análise {{c2::quantitativa}}. Banda {{c3::11}} tem {{c4::incerteza radiométrica}} residual {{c5::~1,7 K}}, desaconselhada pelo {{c6::USGS}}.", "", "m14::sensoriamento-remoto", "geologia-avancado-m14-oa01", "geologia-avancado-m14-a07", "alta"),
]

# Write Basic CSV
with open("14-sensoriamento-remoto/14-sensoriamento-remoto-flashcards-basic.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, delimiter=";")
    writer.writerow(["id", "frente", "verso", "tags", "objetivo", "aula", "dificuldade", "fonte"])
    for card in basic_cards:
        writer.writerow(list(card) + ["Aula do módulo 14"])

# Write Cloze CSV
with open("14-sensoriamento-remoto/14-sensoriamento-remoto-flashcards-cloze.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, delimiter=";")
    writer.writerow(["id", "texto", "extra", "tags", "objetivo", "aula", "dificuldade", "fonte"])
    for card in cloze_cards:
        writer.writerow(list(card) + ["Aula do módulo 14"])

print(f"[OK] Basic flashcards: {len(basic_cards)} cards")
print(f"[OK] Cloze flashcards: {len(cloze_cards)} cards")
print(f"[OK] Total: {len(basic_cards) + len(cloze_cards)} cards")
print(f"\nFiles created:")
print(f"  - 14-sensoriamento-remoto/14-sensoriamento-remoto-flashcards-basic.csv")
print(f"  - 14-sensoriamento-remoto/14-sensoriamento-remoto-flashcards-cloze.csv")
